/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f6e835394237f01fba038726e2d4f9ae)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
